### PR TITLE
go_repository_cache: use -modcacherw if available

### LINKED ISSUE #765: bazel clean fails with permission denied error after running bazel run //:gazelle
### What version of gazelle are you using?

v0.20.0

### What version of rules_go are you using?

v0.22.4

### What version of Bazel are you using?

```ps
> bazel version
Bazelisk version: v1.4.0
Build label: 3.1.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:35:28 2020 (1587551728)
Build timestamp: 1587551728
Build timestamp as int: 1587551728
```

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

- Windows 10 Pro, 1909, build 18363.778
- AMD64
- msys2 installed

### What did you do?

Put the following files:

#### WORKSPACE
```bazel
workspace(name = "bazel_gazelle_repository_cache")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "7b9bbe3ea1fccb46dcfa6c3f3e29ba7ec740d8733370e21cdc8937467b4a4349",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.22.4/rules_go-v0.22.4.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.22.4/rules_go-v0.22.4.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains()

http_archive(
    name = "bazel_gazelle",
    sha256 = "d8c45ee70ec39a57e7a05e5027c32b1576cc7f16d9dd37135b0eddde45cf1b10",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/bazel-gazelle/releases/download/v0.20.0/bazel-gazelle-v0.20.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.20.0/bazel-gazelle-v0.20.0.tar.gz",
    ],
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()
```

#### BUILD.bazel
```bazel
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/yuryu/bazel-gazelle-repository-cache
gazelle(
    name = "gazelle",
)
```

#### main.go
```go
package main

func main() {

}
```

And run `bazel run //:gazelle`, and `bazel clean --expunge`

### What did you expect to see?

`bazel clean --expunge` succeeds.

### What did you see instead?

```ps
PS C:\Users\yuryu\src\bazel-gazelle-repository-cache> bazel run //:gazelle
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:gazelle (56 packages loaded, 6893 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
  bazel-bin/gazelle.exe
INFO: Elapsed time: 67.680s, Critical Path: 8.68s
INFO: 34 processes: 34 local.
INFO: Build completed successfully, 48 total actions
INFO: Build completed successfully, 48 total actions
PS C:\Users\yuryu\src\bazel-gazelle-repository-cache> bazel clean --expunge
INFO: Starting clean.
ERROR: C:/users/yuryu/_bazel_yuryu/7b2tvhyh/external/bazel_gazelle_go_repository_cache/pkg/mod/github.com/!burnt!sushi/toml@v0.3.1/cmd/toml-test-decoder (Permission denied)
```

Bazel fails to access the go repository cache. This also happens with other operations but this was the easiest way to reproduce.

### PR DESCRIPTION
**Pull request by jayconrod**
Fixes #765

### CODE REVIEW

File: cmd/fetch_repo/module.go [hunk 1]
```diff
@@ -45,6 +46,16 @@ func fetchModule(dest, importpath, version, sum string) error {
...
+	// Check whether -modcacherw is supported.
+	// Assume that fetch_repo was built with the same version of Go we're running.
+	modcacherw := false
+	for _, tag := range build.Default.ReleaseTags {
+		if tag == "go1.14" {
+			modcacherw = true
+			break
+		}
+	}
+
```
Comment (dragonsinth) [inline cmd/fetch_repo/module.go:58]: @jayconrod this code seems problematic -- we recently had to change our Go version from the default (a 1.14 build) to 1.13, and all our engineers had to `clean --expunge` because of this code.  We'd get errors like:

```
ERROR: no such package '@com_github_bazelbuild_buildtools//buildifier': failed to fetch com_github_bazelbuild_buildtools: fetch_repo: /private/var/tmp/_bazel_scottb/befbf4792f1e89f7a96261537dac474e-services-go/external/go_sdk/bin/go /private/var/tmp/_bazel_scottb/befbf4792f1e89f7a96261537dac474e-services-go/external/go_sdk/bin/go mod download -json -modcacherw github.com/bazelbuild/buildtools@v0.0.0-20200718160251-b1667ff58f71: flag provided but not defined: -modcacherw
```


Could we just invoke Go here and check the Go binary reported version?

Comment (jayconrod) [reply cmd/fetch_repo/module.go:58]: I'm not sure that would help. It sounds like the problem was that changing the Go version didn't invalidate the `@bazel_gazelle_go_repository_tools` repo. It probably should.

That said, Go 1.13 is no longer supported by the Go team, so `-modcacherw` should just be on unconditionally. 1.13 no longer receives security updates, so I'd strongly encourage you to upgrade.

Comment (dragonsinth) [reply cmd/fetch_repo/module.go:58]: I think it would help in our case, because the invoked Go binary is actually the right version.  I understanding not wanting to support older versions; but in our case we don't want to conflate go version changes with migration to bazel. :/

A better fix would definitely be to fix any dependency invalidation-- gazelle should get rebuild on go version change.  Is that a gazelle fix, or rules go?

Comment (jayconrod) [reply cmd/fetch_repo/module.go:58]: It's a Gazelle issue. I've opened #940 to track it separately.
