### PR TITLE
language/proto: Fixed service definition regexp

### LINKED ISSUE #702: gazelle add grpc compilers attributes on non grpc protos
### What version of gazelle are you using?
0.19.1

### What version of rules_go are you using?
0.19.9

### What version of Bazel are you using?
1.2.1

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Linux asmirnov 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?

1. Create simple .proto:

```protobuf
syntax = proto3;

package bug;

message Foo {
  string service = 1;
}
```

2. Run bazel run //:gazelle

### What did you expect to see?

The `compilers` attribute should not be present in `go_proto_library` if the source .proto does not contain `service` definitions.

### What did you see instead?
BUILD.bazel file contains attribute `compilers = ["@io_bazel_rules_go//proto:go_grpc"]` in go_proto_library definition.

### PR DESCRIPTION
**Pull request by asv**
Fixes #702

### CODE REVIEW

File: language/go/generate_test.go [hunk 1]
```diff
@@ -90,6 +90,7 @@ func TestGenerateRules(t *testing.T) {
 			f.Sync()
 			got := string(bzl.Format(f.File))
 			wantPath := filepath.Join(dir, "BUILD.want")
+			t.Logf("Using %s file for test", wantPath)
```
Comment (jayconrod) [inline language/go/generate_test.go]: Let's drop this log statement.

Comment (asv) [reply language/go/generate_test.go]: OK, but without Log, it is not always obvious on which testdata the problem occurred...

Comment (jayconrod) [reply language/go/generate_test.go]: Each subtest should have the testdata subdirectory as part of its name. Or am I missing something?
