### PR TITLE
fix(language/go): use rules_go apparent name in proto compilers

### LINKED ISSUE #2000: bzlmod gazelle cannot produce a correct BUILD file for grpc.
### What version of gazelle are you using?
0.40.0

### What version of rules_go are you using?

0.50.1

### What version of Bazel are you using?

8.0.0

### Does this issue reproduce with the latest releases of all the above?
yes

### What operating system and processor architecture are you using?
macos arm m2

### What did you do?
Try to build my sample project https://github.com/gator1/rundoo with bazel. 

Had a lot of trouble using WORKSPACE and decided to use all latest. I used bzlmod. 
Cannot make gazelle generate the right BUILD file, it produced reference to io_bazel_rules_go which bazel cannot find the 
repo. 

my project rundoo was built with go build and works fine. It uses grpc where I think bazel/gazelle belmod has trouble with. 

I follow this doc https://github.com/bazel-contrib/rules_go/blob/master/docs/go/core/bzlmod.md

BUILD file is 
```
load("@gazelle//:def.bzl", "gazelle")

gazelle(name = "gazelle")

```

MODULE.bazel
```
bazel_dep(name = "gazelle", version = "0.40.0")
bazel_dep(name = "rules_go", version = "0.50.1")
bazel_dep(name = "rules_proto_grpc", version = "5.0.1")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")

# Download a suitable Go SDK.
go_sdk.download(version = "1.23.3")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
use_repo(go_deps, "com_github_data_dog_go_sqlmock", "com_github_jarcoal_httpmock", "com_github_lib_pq", "com_github_stretchr_testify", "org_golang_google_grpc", "org_golang_google_protobuf")
```
.bazelrc
```
common --enable_bzlmod 
```
.bazelversion
```
8.0.0
```

Passed bazel run //:gazelle with warning
```
bazel run //:gazelle                           
INFO: Analyzed target //:gazelle (2 packages loaded, 105 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 0.380s, Critical Path: 0.03s
INFO: 1 process: 67 action cache hit, 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/gazelle
gazelle: could not parse directive: app/registry //app/registry:go_default_library
        expected gazelle:resolve source-language [import-language] import-string label
gazelle: finding module path for import app/log: go: -d flag is deprecated. -d=true is a no-op
go: malformed module path "app/log": missing dot in first path element
gazelle: finding module path for import app/log: go: -d flag is deprecated. -d=true is a no-op
go: malformed module path "app/log": missing dot in first path element
gazelle: finding module path for import app/log: go: -d flag is deprecated. -d=true is a no-op
go: malformed module path "app/log": missing dot in first path element
```
failed bazel build ...

 bazel build ...     
WARNING: Target pattern parsing failed.
ERROR: Skipping '...': error loading package under directory '': error loading package 'api/v1': Unable to find package for @@[unknown repo 'rules_proto' requested from @@ (did you mean 'rules_go'?)]//proto:defs.bzl: The repository '@@[unknown repo 'rules_proto' requested from @@ (did you mean 'rules_go'?)]' could not be resolved: No repository visible as '@rules_proto' from main repository.
ERROR: error loading package under directory '': error loading package 'api/v1': Unable to find package for @@[unknown repo 'rules_proto' requested from @@ (did you mean 'rules_go'?)]//proto:defs.bzl: The repository '@@[unknown repo 'rules_proto' requested from @@ (did you mean 'rules_go'?)]' could not be resolved: No repository visible as '@rules_proto' from main repository.
INFO: Elapsed time: 0.132s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

I pushed all the changes to https://github.com/gator1/rundoo. Please check its bzlmod branch, the main branch doesn't have bazel stuff. 

### What did you expect to see?
bazel build ... works


### What did you see instead?
```
bazel build ...                                
WARNING: Target pattern parsing failed.
ERROR: Skipping '...': error loading package under directory '': error loading package 'log': Unable to find package for @@[unknown repo 'io_bazel_rules_go' requested from @@]//go:def.bzl: The repository '@@[unknown repo 'io_bazel_rules_go' requested from @@]' could not be resolved: No repository visible as '@io_bazel_rules_go' from main repository.
ERROR: error loading package under directory '': error loading package 'log': Unable to find package for @@[unknown repo 'io_bazel_rules_go' requested from @@]//go:def.bzl: The repository '@@[unknown repo 'io_bazel_rules_go' requested from @@]' could not be resolved: No repository visible as '@io_bazel_rules_go' from main repository.
INFO: Elapsed time: 0.125s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

### PR DESCRIPTION
**Pull request by rdesgroppes**
**What type of PR is this?**

Bug fix

**What package or component does this PR mostly affect?**

language/go

**What does this PR do? Why is it needed?**

In Bzlmod workspaces, the apparent name of the rules_go module defaults to `@rules_go` (or whatever `repo_name` is set to in `MODULE.bazel`).
The default proto compiler labels are hardcoded to `@io_bazel_rules_go`, causing Gazelle to always generate:
```py
go_proto_library(
    ...
    compilers = [
        "@io_bazel_rules_go//proto:go_proto",
        "@io_bazel_rules_go//proto:go_grpc_v2",
    ],
```
... in pure Bzlmod workspaces where `@io_bazel_rules_go` does not exist, this breaks the build.

**Which issues(s) does this PR fix?**

Fixes #2000

**Other notes for review**

Since `Configure()` already resolves `gc.rulesGoRepoName` from the `MODULE.bazel` apparent name mapping, the proposed fix consists in rebuilding the compiler lists from that resolved name whenever they have not been overridden via `# gazelle:go_proto_compilers` and `# gazelle:go_grpc_compilers` directives.

### CODE REVIEW

File: language/go/config.go [hunk 1]
```diff
@@ -523,6 +523,25 @@ func (*goLang) Configure(c *config.Config, rel string, f *rule.File) {
 			// The legacy name used in WORKSPACE.
 			gc.rulesGoRepoName = "io_bazel_rules_go"
 		}
+		if gc.rulesGoRepoName != "io_bazel_rules_go" {
+			reparent := func(compilers []string) []string {
+				out := make([]string, len(compilers))
+				for i, c := range compilers {
+					if after, ok := strings.CutPrefix(c, "@io_bazel_rules_go"); ok {
```
Comment (fmeum) [inline language/go/config.go]: I understand why you did this, but it feels overly generic for something that operates on a hardcoded list of labels anyway. Instead, could you:
1. defer the logic that uses the hardcoded list by not replacing the empty value for the directive (the default) 
2. use the existing `rulesGoRepoName` field when emitting the `compilers` attribute and falling back to the hardcoded list of targets within `rules_go` in that case?

Comment (rdesgroppes) [reply language/go/config.go]: @fmeum I've just updated the PR by filing a 2nd commit that kind of revamps the approach. Would you mind having a second look?

**Comment by jayconrod** [comment]
@mateusz-olczyk I think you added this hard-coding earlier. Do you anticipate any problems from changing this?

**Review by fmeum — APPROVED** [review]

**Comment by mateusz-olczyk** [comment]
@jayconrod, sorry for the late response; I was on vacation.

Definitely, we should rely on the "apparent name" mechanism and fall back to the WORKSPACE default only if a module specification is missing in `MODULE.bazel`.

> I think you added this hard-coding earlier.

Not exactly, yet I touched similar elements in #2284. The main change was located in `language/proto/fix.go`. Files under `language/go` were not changed.

> Do you anticipate any problems from changing this?

I do not foresee any problems at this time. We will react accordingly when bumping `bazel-gazelle` at `gazelle_cc`.

File: language/go/config.go (hunk 1 above)
Comment (rdesgroppes) [reply language/go/config.go]: Approved => resolving.

**Comment by rdesgroppes** [comment]
Shall we proceed?

**Review by jayconrod — APPROVED** [review]
