### PR TITLE
Fix kinds and stmt

### LINKED ISSUE #1612: mismatched rules kind & stmt
### What version of gazelle are you using?
[v0.32.0 ](https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.32.0)

### What version of rules_go are you using?
[v0.41.0](https://github.com/bazelbuild/rules_go/releases/tag/v0.41.0)

### What version of Bazel are you using?
bazel 6.3.2

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Ubuntu 20.04.6 LTS x86_64

### What did you do?
`BUILD.bazel` contains rule packed into struct:
```bzl
selects.config_setting_group(
    name = "a",
    match_any = [
        "//:config_a",
        "//:config_b",
    ],
)
```

Parsed rule from the input by [ruleFromExpr()](https://github.com/bazelbuild/bazel-gazelle/blob/master/rule/rule.go#L757) function sets it's _kind_ to a parsed expression:
```go
kind := call.X
```
which in this case is:
```go
DotExpr{
    X: bzl.Ident{Name: "selects"},
    Name: "config_setting_group"
}
```

However when one wants to generate such rule with [NewRule()](https://github.com/bazelbuild/bazel-gazelle/blob/master/rule/rule.go#L723) 
```go
r := rule.NewRule("selects.config_setting_group", "config_group_name")
```
the kind will be set to 
```go
kindIdent := &bzl.Ident{Name: kind}
```

This changed the behavior e.g. for fixing loads where different statement is parsed. 

### What did you expect to see?
Both ways of creating rules should allow instantiating conforming rules to each other.
Kind should be exactly the same to be matched with type or by [bzl.FormatString()](https://github.com/bazelbuild/bazel-gazelle/blob/master/vendor/github.com/bazelbuild/buildtools/build/print.go#L56)
Identifier to search for load symbols should be also the same for both rules (parsed & generated).

### What did you see instead?
for loads:
```go
var loads = []rule.LoadInfo{
	{
		Name: "@bazel_skylib//lib:selects.bzl",
		Symbols: []string{
			"selects",
		},
	},
}
```
and an empty `BUILD.bazel` file (no `selects.config_setting_group` rules inside) load statement is not resolved correctly therefore it is missed in the final output.

### PR DESCRIPTION
**Pull request by birunts**
**What type of PR is this?**
Bug fix

**What package or component does this PR mostly affect?**
internal/language
rule
tests

**What does this PR do? Why is it needed?**
Bazel allows to pack rules or macros within a struct, e.g. convenience interfaces for select()
(see https://github.com/bazelbuild/bazel-skylib/blob/main/lib/selects.bzl)

Generated rule of `selects.config_setting_group` by [rule.NewRule()](https://github.com/bazelbuild/bazel-gazelle/blob/master/rule/rule.go#L723) is different with the rule parsed from the input file i.e. [ruleFromExpr()](https://github.com/bazelbuild/bazel-gazelle/blob/master/rule/rule.go#L757) in a way of different _kind_ and identifier when fixing loads ([FixLoads()](https://github.com/bazelbuild/bazel-gazelle/blob/master/merger/fix.go#L31)).

Newly generated rule:
```go
r := rule.NewRule("selects.config_setting_group", "config_group_name")
```
together with loads:
```go
var loads = []rule.LoadInfo{
	{
		Name: "@bazel_skylib//lib:selects.bzl",
		Symbols: []string{
			"selects",
		},
	},
}
```
should produce in the `BUILD.bazel` output::
```bzl
load("@bazel_skylib//lib:selects.bzl", "selects")

selects.config_setting_group(
    name = "config_group_name",
    ...
)
```

**Which issues(s) does this PR fix?**

Fixes #1612

**Other notes for review**

### CODE REVIEW

File: rule/rule.go [hunk 1]
```diff
@@ -721,8 +721,20 @@ type Rule struct {
...
 func NewRule(kind, name string) *Rule {
+	var call *bzl.CallExpr
 	kindIdent := &bzl.Ident{Name: kind}
-	call := &bzl.CallExpr{X: kindIdent}
+
+	parts := strings.Split(kind, ".")
+	if len(parts) > 1 {
+		// Create the same `CallExpr` like parser does
+		call = &bzl.CallExpr{X: &bzl.DotExpr{
+			Name: strings.Join(parts[1:], "."),
```
Comment (fmeum) [inline rule/rule.go:731]: I would have expected multiple `.`s to result in nested `DotExpr`s. Which existing part of Gazelle doesn't do this?

Comment (birunts) [reply rule/rule.go:731]: Yeah, you're right. I should have checked it more carefully. I'll correct that.

File: rule/rule.go [hunk 2]
```diff
@@ -730,8 +730,16 @@ type attrValue struct {
...
+	var call *bzl.CallExpr
 	kindIdent := &bzl.Ident{Name: kind}
-	call := &bzl.CallExpr{X: kindIdent}
+
+	parts := strings.Split(kind, ".")
+	if len(parts) > 1 {
+		call = &bzl.CallExpr{X: createDotExpr(parts)}
+	} else {
+		call = &bzl.CallExpr{X: kindIdent}
+	}
```
Comment (fmeum) [inline rule/rule.go:741]: Could you extract out this part into `createDotExpr`? It can return a generic `Expr` that is either a `DotExpr` or an `Ident`.

**Review by fmeum — APPROVED** [review]
Looks good now, with one more comment.

Please mention me after making your changes as I don't get notifications for pushed on PRs.

File: rule/rule.go (hunk 2 above)
Comment (birunts) [reply rule/rule.go]: Sure, changes updated.

File: rule/rule.go [hunk 3]
```diff
@@ -730,8 +730,11 @@ type attrValue struct {
 
 // NewRule creates a new, empty rule with the given kind and name.
 func NewRule(kind, name string) *Rule {
+	var call *bzl.CallExpr
 	kindIdent := &bzl.Ident{Name: kind}
```
Comment (fmeum) [inline rule/rule.go:734]: Thanks for the update, just one quick question: Why do we still need the `kindIdent`? Couldn't we set `Rule.kind` to the `DotExpr` or would that break other parts of Gazelle? Having two different AST representations in this structure makes me a bit worried.

Comment (birunts) [reply rule/rule.go:734]: Actually I'm not sure to be honest, I don't know all Gazelle specifics, but afair `kind` needs to conform to one defined in `rule.KindInfo` map, e.g. for
```
var kinds = map[string]rule.KindInfo{
	"selects.config_setting_group": {
		...
	},
}
```
with `&bzl.Ident{Name: kind}` is matched to `selects.config_setting_group` string. If the same kind can be grabbed form the `DotExpr` then it will work as you're saying.

Comment (birunts) [reply rule/rule.go:734]: `Rule.Kind()` string is made of `bzl.createDotExpr()` so it should work :)

**Review by fmeum — APPROVED** [review]
Looks great, thanks!
