### PR TITLE
[cmd/fetch_repo] make cache corruption failures more clear

### LINKED ISSUE #1774: new gazelle v0.36.0 fails with Go sum mismatches
### What version of gazelle are you using?

https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.36.0

### What version of rules_go are you using?

https://github.com/bazelbuild/rules_go/releases/tag/v0.46.0

### What version of Bazel are you using?

7.1.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux AMD 64

### What did you do?

Darwin ARM 64

### What did you expect to see?

Successful gazelle run

### What did you see instead?
```
ERROR: An error occurred during the fetch of repository 'com_github_procyon_projects_chrono':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_johankj/cf455b47f50dd837b297aa6fcdb2d775/external/bazel_gazelle/internal/go_repository.bzl", line 263, column 17, in _go_repository_impl
		fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch com_github_procyon_projects_chrono: fetch_repo: resulting module with sum h1:l0VwRF053FgTUXw2dMwpHYBY9d0SuZOAmjSBOvdeO1Y=; expected sum h1:edOeKOW2eGP8j3gI6wQWzyoUM0njjuxOlbtpguIkXqQ=
ERROR: /Users/johankj/Uber/go-code-odin/WORKSPACE:68:26: fetching go_repository rule //external:com_github_procyon_projects_chrono: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_johankj/cf455b47f50dd837b297aa6fcdb2d775/external/bazel_gazelle/internal/go_repository.bzl", line 263, column 17, in _go_repository_impl
		fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch com_github_procyon_projects_chrono: fetch_repo: resulting module with sum h1:l0VwRF053FgTUXw2dMwpHYBY9d0SuZOAmjSBOvdeO1Y=; expected sum h1:edOeKOW2eGP8j3gI6wQWzyoUM0njjuxOlbtpguIkXqQ=
Analyzing: target //src/code.uber.internal/compute/foosbot:foosbot (462 packages loaded, 2947 targets configured)
```
However this is a pretty normal `go_repository` rule:
```
 go_repository(
        name = "com_github_procyon_projects_chrono",
        build_extra_args = ["-go_naming_convention_external=go_default_library"],
        build_file_generation = "on",
        build_file_proto_mode = "disable",
        importpath = "github.com/procyon-projects/chrono",
        sum = "h1:edOeKOW2eGP8j3gI6wQWzyoUM0njjuxOlbtpguIkXqQ=",
        version = "v1.0.0",
    )
```

### PR DESCRIPTION
**Pull request by tyler-french**
This failure was confusing to our users. We should make more clear error messages in cases when a `GOMODCACHE` might be corrupt.

Resolves #1774

Example failure:
```
ERROR: /home/user/go-code/WORKSPACE:69:26: fetching go_repository rule //external:com_github_bazelbuild_remote_apis: Traceback (most recent call last):
        File "/home/user/.cache/bazel/_bazel_tfrench/b97476d719d716accead0f2d5b93104f/external/bazel_gazelle/internal/go_repository.bzl", line 263, column 17, in _go_repository_impl
                fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch com_github_bazelbuild_remote_apis: fetch_repo: resulting module with sum h1:xhO5v3Ac039HesaPqoVUwOy4WhRRJbmo9om245kp+AY=; expected sum h1:xhO5v3Ac039HesaPqoVUwOy4WhRRJbmo9om245kp+AY=, Please try clearing your module cache directory "/home/user/go-code/pkg/mod"
ERROR: Error computing the main repository mapping: no such package '@@com_github_bazelbuild_remote_apis//': failed to fetch com_github_bazelbuild_remote_apis: fetch_repo: resulting module with sum h1:xhO5v3Ac039HesaPqoVUwOy4WhRRJbmo9om245kp+AY=; expected sum h1:xhO5v3Ac039HesaPqoVUwOy4WhRRJbmo9om245kp+AY=, Please try clearing your module cache directory "/home/user/go-code/pkg/mod"
INFO: Build Event Protocol files produced successfully.
Computing main repo mapping: 
WARNING:Bazel failed with exit code 1
```

### CODE REVIEW

**Review by fmeum — APPROVED** [review]

File: cmd/fetch_repo/go_mod_download.go [hunk 1]
```diff
@@ -44,34 +44,28 @@ func runGoModDownload(dl *GoModDownloadResult, dest string, importpath string, v
 
 	cmd.Stdout = buf
 	cmd.Stderr = bufErr
-	fmt.Printf("Running: %s %s\n", cmd.Path, strings.Join(cmd.Args, " "))
```
Comment (tyler-french) [inline cmd/fetch_repo/go_mod_download.go:47]: A little bit of cleanup. I don't think we should be printing these to output.

**Review by fmeum — APPROVED** [review]

File: cmd/fetch_repo/go_mod_download.go [hunk 2]
```diff
@@ -44,34 +44,28 @@ func runGoModDownload(dl *GoModDownloadResult, dest string, importpath string, v
...
+				return fmt.Errorf("go mod download exec error: %s %q: %s", cmd.Path, strings.Join(cmd.Args, " "), bufErr.String())
 			}
+			return fmt.Errorf("go mod download exec error: %s %s: %v", cmd.Path, strings.Join(cmd.Args, " "), dlErr)
 		}
 	}
 
 	// Parse the JSON output.
 	if err := json.Unmarshal(buf.Bytes(), &dl); err != nil {
 		if bufErr.Len() > 0 {
-			return fmt.Errorf("3%s %s: %s", cmd.Path, strings.Join(cmd.Args, " "), bufErr.Bytes())
```
Comment (tyler-french) [inline cmd/fetch_repo/go_mod_download.go:62]: @fmeum Do you know what this `3` and `4` (And above `!` and `!!` are coming from?

File: cmd/fetch_repo/go_mod_download.go [hunk 3]
```diff
@@ -44,34 +44,28 @@ func runGoModDownload(dl *GoModDownloadResult, dest string, importpath string, v
...
-		} else {
-			return fmt.Errorf("4%s %s: error parsing JSON: %v error: %v", cmd.Path, strings.Join(cmd.Args, " "), buf, err)
+			return fmt.Errorf("go mod download output format: `%s %s`: parsing JSON: %q stderr: %q error: %w", cmd.Path, strings.Join(cmd.Args, " "), buf.String(), bufErr.String(), err)
 		}
+		return fmt.Errorf("go mod download output format: `%s %s`: parsing JSON: %q error: %w", cmd.Path, strings.Join(cmd.Args, " "), buf.String(), err)
 	}
 	if dl.Error != "" {
-		return errors.New(dl.Error)
+		return errors.Join(errors.New(dl.Error), dlErr)
```
Comment (tyler-french) [inline cmd/fetch_repo/go_mod_download.go:65]: We should also join in the `dlErr` if we return here

File: cmd/fetch_repo/go_mod_download.go [hunk 4]
```diff
@@ -44,34 +44,28 @@ func runGoModDownload(dl *GoModDownloadResult, dest string, importpath string, v
 
 	cmd.Stdout = buf
 	cmd.Stderr = bufErr
-	fmt.Printf("Running: %s %s\n", cmd.Path, strings.Join(cmd.Args, " "))
 	dlErr := cmd.Run()
 	if dlErr != nil {
 		if _, ok := dlErr.(*exec.ExitError); !ok {
 			if bufErr.Len() > 0 {
-				return fmt.Errorf("!%s %s: %s", cmd.Path, strings.Join(cmd.Args, " "), bufErr.Bytes())
```
Comment (tyler-french) [inline cmd/fetch_repo/go_mod_download.go:52]: `bufErr.Bytes()` will output bytes which is not intended for `%s`. Moving to `.String()`

File: cmd/fetch_repo/go_mod_download.go (hunk 2 above)
Comment (fmeum) [reply cmd/fetch_repo/go_mod_download.go:62]: I think that this was just an oversight, thanks for changing the messages.

**Review by fmeum — APPROVED** [review]
