### PR TITLE
go/visibility: expand visibility to other repos that are sibling to internal/

### LINKED ISSUE #960: language/go: wrong visibility for module path ending with "internal"
### What version of gazelle are you using?
v0.22.2:
```
http_archive(
    name = "bazel_gazelle",
    sha256 = "b85f48fa105c4403326e9525ad2b2cc437babaa6e15a3fc0b1dbab0ab064bc7c",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.22.2/bazel-gazelle-v0.22.2.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.22.2/bazel-gazelle-v0.22.2.tar.gz",
    ],
)
```

### What version of rules_go are you using?
v0.24.5
```
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "d1ffd055969c8f8d431e2d439813e42326961d0942bdf734d2c95dc30c369566",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.24.5/rules_go-v0.24.5.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.24.5/rules_go-v0.24.5.tar.gz",
    ],
)
```

### What version of Bazel are you using?
```
Bazelisk version: v1.7.4
Build label: 3.7.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Nov 24 17:38:30 2020 (1606239510)
Build timestamp: 1606239510
Build timestamp as int: 1606239510
```
### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Linux Debian Buster amd64
```go.mod
module <SOME_MODULE>

go 1.13

require (
    golang.org/x/net v0.0.0-20201110031124-69a78807bb2b // indirect
    modernc.org/ccgo v1.0.0 // indirect
    modernc.org/ccir v1.0.0 // indirect
    modernc.org/internal v1.0.0 // indirect
    modernc.org/memory v1.0.4 // indirect
    modernc.org/sqlite v1.0.0
)
```

```main.go
package main

import (
    "database/sql"
    "fmt"

    _ "modernc.org/sqlite"
)

func main() {
    fmt.Println("Opening in-memory sqlite database")
    db, err := sql.Open("sqlite", ":memory:")
    if err != nil {
        fmt.Println(err)
        return
    }

    if _, err = db.Exec(`
DROP TABLE IF EXISTS sqlite;
CREATE TABLE sqlite(i);
    `); err != nil {
        fmt.Println(err)
        return
    }
    fmt.Println("Done")
} 
```

```BUILD.bazel
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix <SOME_MODULE>
gazelle(name = "gazelle")

go_library(
    name = "sqlite_lib",
    srcs = ["main.go"],
    importpath = "<SOME_MODULE>",
    visibility = ["//visibility:private"],
    deps = ["@org_modernc_sqlite//:sqlite"],
)

go_binary(
    name = "sqlite",
    embed = [":sqlite_lib"],
    visibility = ["//visibility:public"],
)
```

### What did you do?
I created a proof-of-concept repo that tries to import modernc.org/sqlite v1.0.0

### What did you expect to see?
I expected it to build, since go build works

### What did you see instead?
```
ERROR: /home/douglas/.cache/bazel/_bazel_douglas/cea54a25b012f5a3480c4aba3dcd4d3f/external/org_modernc_ccgo/crt/BUILD.bazel:3:11: in go_library rule @org_modernc_ccgo//crt:crt: target '@org_modernc_internal//buffer:buffer' is not visible from target '@org_modernc_ccgo//crt:crt'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//vanilla/sqlite:sqlite' failed; build aborted: Analysis of target '@org_modernc_ccgo//crt:crt' failed
INFO: Elapsed time: 2.927s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (13 packages loaded, 362 targets configured)
FAILED: Build did NOT complete successfully (13 packages loaded, 362 targets configured)
```

### PR DESCRIPTION
**Pull request by robfig**
**What type of PR is this?**

Bug fix

**What package or component does this PR mostly affect?**

language/go

**Which issues(s) does this PR fix?**

Fixes #960

### CODE REVIEW

File: language/go/generate.go [hunk 1]
```diff
@@ -712,7 +712,15 @@ func (g *generator) commonVisibility(importPath string) []string {
 		parent := strings.TrimSuffix(g.rel[:relIndex], "/")
 		visibility = append(visibility, fmt.Sprintf("//%s:__subpackages__", parent))
 	} else if importIndex >= 0 {
+		// This entire module is within an internal directory.
+		// Identify other repos which should have access too.
 		visibility = append(visibility, "//:__subpackages__")
+		for _, repo := range g.c.Repos {
+			if strings.HasPrefix(repo.AttrString("importpath"), importPath[:importIndex]) {
```
Comment (jayconrod) [inline language/go/generate.go:719]: Use `pathtools.HasPrefix` instead of `strings.HasPrefix`. It will automatically trim the trailing slash and guard against partial element matches.

**Review by jayconrod — APPROVED** [review]
This looks good, thanks for fixing this. One small comment.

I think the test failures were due to 1.16beta1 getting removed. I've updated WORKSPACE to 1.16, so if you update to `master`, it should turn green.

File: language/go/generate.go (hunk 1 above)
Comment (robfig) [reply language/go/generate.go:719]: Good catch, done

**Comment by robfig** [comment]
Addressed your comment and rebased. Thanks for the review

**Comment by jayconrod** [comment]
Looks good. Merge when ready :)

**Comment by robfig** [comment]
Huzzah!
